# Generated by Django 4.1.11 on 2023-10-04 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='edu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=50)),
                ('field_of_study', models.CharField(blank=True, max_length=50)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField()),
                ('grade_choice', models.CharField(choices=[('CGPA', 'CGPA'), ('PERCENTAGE', '%')], max_length=10)),
                ('grade', models.FloatField()),
                ('degree_link', models.FileField(default=None, upload_to='degree')),
            ],
        ),
        migrations.CreateModel(
            name='exp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('Title', models.CharField(max_length=60)),
                ('start_date', models.DateField()),
                ('still_working', models.BooleanField(default=False)),
                ('end_date', models.DateField(blank=True)),
                ('total_exp_in_months', models.IntegerField()),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_title', models.CharField(max_length=100)),
                ('skills_used', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('github_link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(default=None, upload_to='resume/')),
            ],
        ),
    ]
