# Generated by Django 4.1.11 on 2023-10-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edu',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
