# Generated by Django 4.1.11 on 2023-10-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_edu_degree_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edu',
            name='degree_link',
            field=models.FileField(blank=True, default=None, null=True, upload_to='degree'),
        ),
    ]
